CXX = g++
CFLAGS = -Wall -std=c++11
OBJECTS_PART1 = day1.cpp
OBJECTS_PART2 = day1_2.cpp
OUTPUT = day1

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT)