CXX = g++
CFLAGS = -Wall -std=c++11
OBJECTS_PART1 = day3.cpp
OBJECTS_PART2 = day3_2.cpp
OUTPUT = day3

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT)