CXX = g++
CFLAGS = -Wall -std=c++11
OBJECTS_PART1 = day9.cpp
OBJECTS_PART2 = day9_2.cpp
OUTPUT = day9

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT)