CXX = g++
CFLAGS = -Wall -std=c++11
OBJECTS_PART1 = day10.cpp
OBJECTS_PART2 = day10_2.cpp
OUTPUT = day10

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT)