CXX = g++
CFLAGS = -Wall -std=c++11
OBJECTS_PART1 = day7.cpp
OBJECTS_PART2 = day7_2.cpp
OUTPUT = day7

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT)